version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: online_school_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: online_school
      POSTGRES_USER: online_school_user
      POSTGRES_PASSWORD: online_school_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U online_school_user -d online_school"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - online_school_network

  redis:
    image: redis:7-alpine
    container_name: online_school_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - online_school_network
      
  # Django приложение
  web:
    build: .
    container_name: online_school_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=online_school
      - DB_USER=online_school_user
      - DB_PASSWORD=online_school_pass
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - online_school_network
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application
      "

  # Celery worker
  celery_worker:
    build: .
    container_name: online_school_celery_worker
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=online_school
      - DB_USER=online_school_user
      - DB_PASSWORD=online_school_pass
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - online_school_network
    command: celery -A config worker --loglevel=info

  # Celery beat
  celery_beat:
    build: .
    container_name: online_school_celery_beat
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=online_school
      - DB_USER=online_school_user
      - DB_PASSWORD=online_school_pass
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - online_school_network
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  online_school_network:
    driver: bridge